# macOS-only links and packages, imported by the Mac host files.
{ config, pkgs, ... }:
let
  link = path: config.lib.file.mkOutOfStoreSymlink "${config.dotfiles.repoDir}/${path}";
in
{
  imports = [ ./repo.nix ];

  home.packages = [
    pkgs.terminal-notifier
    pkgs.sketchybar
    pkgs.jankyborders
  ];

  home.file = {
    ".hammerspoon".source = link "hammerspoon/.hammerspoon";

    # Typora owns its themes directory, so the generated CSS files are linked
    # individually; a new palette needs a switch.
    "Library/Application Support/abnerworks.Typora/themes/dark.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/dark.css";
    "Library/Application Support/abnerworks.Typora/themes/light.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/light.css";
    "Library/Application Support/abnerworks.Typora/themes/ft.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/ft.css";
    "Library/Application Support/abnerworks.Typora/themes/flexoki_dark.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/flexoki_dark.css";
    "Library/Application Support/abnerworks.Typora/themes/flexoki_light.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/flexoki_light.css";
  };

  xdg.configFile = {
    # A whole-directory link, so generated colors-* files inside it follow
    # regeneration without a switch.
    "wezterm".source = link "wezterm/.config/wezterm";

    # mode-borders-*.sh are generated by the theme generator.
    "aerospace/aerospace.toml".source = link "aerospace/.config/aerospace/aerospace.toml";
    "aerospace/mode-borders.sh".source = link "aerospace/.config/aerospace/mode-borders.sh";
    "aerospace/mode-borders-dark.sh".source = link "aerospace/.config/aerospace/mode-borders-dark.sh";
    "aerospace/mode-borders-light.sh".source = link "aerospace/.config/aerospace/mode-borders-light.sh";
    "aerospace/mode-borders-ft.sh".source = link "aerospace/.config/aerospace/mode-borders-ft.sh";
    "aerospace/mode-borders-flexoki_dark.sh".source = link "aerospace/.config/aerospace/mode-borders-flexoki_dark.sh";
    "aerospace/mode-borders-flexoki_light.sh".source = link "aerospace/.config/aerospace/mode-borders-flexoki_light.sh";
    "aerospace/workspace-refresh".source = link "aerospace/.config/aerospace/workspace-refresh";
    "sketchybar/sketchybarrc".source = link "sketchybar/.config/sketchybar/sketchybarrc";
    "sketchybar/assets".source = link "sketchybar/.config/sketchybar/assets";
    "sketchybar/items".source = link "sketchybar/.config/sketchybar/items";
    "sketchybar/lib".source = link "sketchybar/.config/sketchybar/lib";
    "sketchybar/plugins".source = link "sketchybar/.config/sketchybar/plugins";
    "sketchybar/render".source = link "sketchybar/.config/sketchybar/render";
  };
}
