# Out-of-store links into the repo checkout, so editing a file needs no switch.
{ config, ... }:
let
  link = path: config.lib.file.mkOutOfStoreSymlink "${config.dotfiles.repoDir}/${path}";
in
{
  imports = [ ./repo.nix ];

  home.file = {
    # bash entry files
    ".bash-preexec.sh".source = link "bash/.bash-preexec.sh";
    ".bash_profile".source = link "bash/.bash_profile";
    ".bashrc".source = link "bash/.bashrc";
    ".profile".source = link "bash/.profile";

    # zsh entry files
    ".zshenv".source = link "zsh/.zshenv";
    ".zprofile".source = link "zsh/.zprofile";
    ".zshrc".source = link "zsh/.zshrc";

    # Claude Code writes into ~/.claude, so only these entries are linked.
    # settings.json and machine.md come from the machine repo.
    ".claude/CLAUDE.md".source = link "claude/.claude/CLAUDE.md";
    ".claude/commands".source = link "claude/.claude/commands";
    ".claude/hooks".source = link "claude/.claude/hooks";
    ".claude/output-styles".source = link "claude/.claude/output-styles";
    ".claude/statusline-command.sh".source = link "claude/.claude/statusline-command.sh";

    # Pi writes into ~/.pi, so only these entries are linked. The themes dir
    # link keeps generated palettes visible without a switch.
    ".pi/agent/extensions/dotfiles-theme.ts".source = link "pi/.pi/agent/extensions/dotfiles-theme.ts";
    ".pi/agent/themes".source = link "pi/.pi/agent/themes";

    ".hammerspoon".source = link "hammerspoon/.hammerspoon";

    # Typora owns its themes directory, so the generated CSS files are linked
    # individually; a new palette needs a switch.
    "Library/Application Support/abnerworks.Typora/themes/dark.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/dark.css";
    "Library/Application Support/abnerworks.Typora/themes/light.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/light.css";
    "Library/Application Support/abnerworks.Typora/themes/ft.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/ft.css";
    "Library/Application Support/abnerworks.Typora/themes/flexoki_dark.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/flexoki_dark.css";
    "Library/Application Support/abnerworks.Typora/themes/flexoki_light.css".source =
      link "typora/Library/Application Support/abnerworks.Typora/themes/flexoki_light.css";
  };

  xdg.configFile = {
    # Editors. Neovim owns ~/.config/nvim (it writes nvim.log there), so only
    # the config entries are linked; lazy.nvim writes lazy-lock.json through
    # its link into the repo.
    "nvim/init.vim".source = link "nvim/.config/nvim/init.vim";
    "nvim/lua".source = link "nvim/.config/nvim/lua";
    "nvim/after".source = link "nvim/.config/nvim/after";
    "nvim/colors".source = link "nvim/.config/nvim/colors";
    "nvim/lazy-lock.json".source = link "nvim/.config/nvim/lazy-lock.json";
    "vim".source = link "vim/.config/vim";

    # Terminal, prompt and jj. tmux and wezterm are whole-directory links, and
    # generated colors-* files inside them follow regeneration without a switch.
    "tmux".source = link "tmux/.config/tmux";
    "wezterm".source = link "wezterm/.config/wezterm";
    "starship.toml".source = link "starship/.config/starship.toml";
    # jj identity comes from the machine repo's conf.d fragment.
    "jj/config.toml".source = link "jj/.config/jj/config.toml";

    # macOS UI automation; mode-borders-*.sh are generated by the theme generator.
    "aerospace/aerospace.toml".source = link "aerospace/.config/aerospace/aerospace.toml";
    "aerospace/mode-borders.sh".source = link "aerospace/.config/aerospace/mode-borders.sh";
    "aerospace/mode-borders-dark.sh".source = link "aerospace/.config/aerospace/mode-borders-dark.sh";
    "aerospace/mode-borders-light.sh".source = link "aerospace/.config/aerospace/mode-borders-light.sh";
    "aerospace/mode-borders-ft.sh".source = link "aerospace/.config/aerospace/mode-borders-ft.sh";
    "aerospace/mode-borders-flexoki_dark.sh".source = link "aerospace/.config/aerospace/mode-borders-flexoki_dark.sh";
    "aerospace/mode-borders-flexoki_light.sh".source = link "aerospace/.config/aerospace/mode-borders-flexoki_light.sh";
    "aerospace/workspace-refresh".source = link "aerospace/.config/aerospace/workspace-refresh";
    "sketchybar/sketchybarrc".source = link "sketchybar/.config/sketchybar/sketchybarrc";
    "sketchybar/assets".source = link "sketchybar/.config/sketchybar/assets";
    "sketchybar/items".source = link "sketchybar/.config/sketchybar/items";
    "sketchybar/lib".source = link "sketchybar/.config/sketchybar/lib";
    "sketchybar/plugins".source = link "sketchybar/.config/sketchybar/plugins";
    "sketchybar/render".source = link "sketchybar/.config/sketchybar/render";

    # Shared shell layer; fzf-theme-*.sh are generated by the theme generator.
    "shell/env.sh".source = link "shell/.config/shell/env.sh";
    "shell/env.local.example.sh".source = link "shell/.config/shell/env.local.example.sh";
    "shell/interactive.sh".source = link "shell/.config/shell/interactive.sh";
    "shell/fzf-theme-dark.sh".source = link "shell/.config/shell/fzf-theme-dark.sh";
    "shell/fzf-theme-flexoki_dark.sh".source = link "shell/.config/shell/fzf-theme-flexoki_dark.sh";
    "shell/fzf-theme-flexoki_light.sh".source = link "shell/.config/shell/fzf-theme-flexoki_light.sh";
    "shell/fzf-theme-ft.sh".source = link "shell/.config/shell/fzf-theme-ft.sh";
    "shell/fzf-theme-light.sh".source = link "shell/.config/shell/fzf-theme-light.sh";
  };
}
