# Out-of-store links into the repo checkout, so editing a file needs no switch.
{ config, ... }:
let
  link = path: config.lib.file.mkOutOfStoreSymlink "${config.dotfiles.repoDir}/${path}";
in
{
  imports = [ ./repo.nix ];

  home.file = {
    # bash entry files
    ".bash-preexec.sh".source = link "bash/.bash-preexec.sh";
    ".bash_profile".source = link "bash/.bash_profile";
    ".bashrc".source = link "bash/.bashrc";
    ".profile".source = link "bash/.profile";

    # zsh entry files
    ".zshenv".source = link "zsh/.zshenv";
    ".zprofile".source = link "zsh/.zprofile";
    ".zshrc".source = link "zsh/.zshrc";

    # Claude Code writes into ~/.claude, so only these entries are linked.
    # settings.json and machine.md come from the machine repo.
    ".claude/CLAUDE.md".source = link "claude/.claude/CLAUDE.md";
    ".claude/writing-comments.md".source = link "claude/.claude/writing-comments.md";
    ".claude/commands".source = link "claude/.claude/commands";
    ".claude/hooks".source = link "claude/.claude/hooks";
    ".claude/output-styles".source = link "claude/.claude/output-styles";
    ".claude/statusline-command.sh".source = link "claude/.claude/statusline-command.sh";

    # Pi writes into ~/.pi, so only these entries are linked. The themes dir
    # link keeps generated palettes visible without a switch.
    ".pi/agent/extensions/dotfiles-theme.ts".source = link "pi/.pi/agent/extensions/dotfiles-theme.ts";
    ".pi/agent/themes".source = link "pi/.pi/agent/themes";
  };

  xdg.configFile = {
    # Editors. Neovim owns ~/.config/nvim (it writes nvim.log there), so only
    # the config entries are linked; vim.pack writes nvim-pack-lock.json
    # through its link into the repo.
    "nvim/init.vim".source = link "nvim/.config/nvim/init.vim";
    "nvim/lua".source = link "nvim/.config/nvim/lua";
    "nvim/after".source = link "nvim/.config/nvim/after";
    "nvim/colors".source = link "nvim/.config/nvim/colors";
    "nvim/nvim-pack-lock.json".source = link "nvim/.config/nvim/nvim-pack-lock.json";
    "vim".source = link "vim/.config/vim";

    # Terminal, prompt and jj. tmux is a whole-directory link, and generated
    # colors-* files inside it follow regeneration without a switch.
    "tmux".source = link "tmux/.config/tmux";
    "starship.toml".source = link "starship/.config/starship.toml";
    # jj identity comes from the machine repo's conf.d fragment.
    "jj/config.toml".source = link "jj/.config/jj/config.toml";

    # Shared shell layer; fzf-theme-*.sh are generated by the theme generator.
    "shell/env.sh".source = link "shell/.config/shell/env.sh";
    "shell/env.local.example.sh".source = link "shell/.config/shell/env.local.example.sh";
    "shell/interactive.sh".source = link "shell/.config/shell/interactive.sh";
    "shell/fzf-theme-dark.sh".source = link "shell/.config/shell/fzf-theme-dark.sh";
    "shell/fzf-theme-flexoki_dark.sh".source = link "shell/.config/shell/fzf-theme-flexoki_dark.sh";
    "shell/fzf-theme-flexoki_light.sh".source = link "shell/.config/shell/fzf-theme-flexoki_light.sh";
    "shell/fzf-theme-ft.sh".source = link "shell/.config/shell/fzf-theme-ft.sh";
    "shell/fzf-theme-light.sh".source = link "shell/.config/shell/fzf-theme-light.sh";
  };
}
