#!/bin/sh
# Paired with the tmux.conf SSH_AUTH_SOCK override: https://werat.dev/blog/happy-ssh-agent-forwarding/
if [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock"
fi
