-- Public colorscheme API and Alabaster highlight definitions.
-- Palettes live in lua/colors/<name>.lua (generated from palettes/<name>.lua)
-- Usage: require("colors").apply("light"), require("colors").apply_env_or_default(),
-- or require("colors").detect_and_apply() for OSC 11 fallback/manual redetect.

local util = require("colors.util")
local windows = require("colors.windows")

local blend_hex = util.blend_hex
local is_light_bg = util.is_light_bg

local M = {}
M.markdown_hl_ns = windows.markdown_hl_ns
M.zen_hl_ns = windows.zen_hl_ns
M.zen_markdown_hl_ns = windows.zen_markdown_hl_ns
M.diff_hl_ns = windows.diff_hl_ns
M.diff_markdown_hl_ns = windows.diff_markdown_hl_ns

M.default = "light"

-- The currently active palette table
M.active = nil

-- bg hex (lowercase, no #) → palette name, generated by palettes/generate.lua.
-- This is only used by the OSC 11 fallback/manual redetect path; normal
-- startup uses DOTFILES_THEME directly.
local registry_ok, registry = pcall(require, "colors.registry")
M.registry = registry_ok and registry or {}

local function normalize_theme_name(name)
  if type(name) ~= "string" then
    return nil
  end

  name = vim.trim(name)
  if name == "" then
    return nil
  end

  name = name:gsub("^colors_", "")
  if not name:match("^[%w_-]+$") then
    return nil
  end

  return name
end

M.normalize_theme_name = normalize_theme_name

function M.colorscheme_exists(name)
  name = normalize_theme_name(name)
  if not name then
    return false
  end

  return #vim.api.nvim_get_runtime_file("colors/colors_" .. name .. ".lua", false) > 0
end

function M.env_theme()
  local name = normalize_theme_name(vim.env.DOTFILES_THEME)
  if name and M.colorscheme_exists(name) then
    return name
  end

  return nil
end

function M.apply_theme(name, opts)
  opts = opts or {}
  name = normalize_theme_name(name)
  if not name then
    return nil
  end

  if opts.check_exists ~= false and not M.colorscheme_exists(name) then
    if opts.notify ~= false then
      vim.notify("Colorscheme not found: colors_" .. name, vim.log.levels.WARN)
    end
    return nil
  end

  local ok, err = pcall(vim.cmd.colorscheme, "colors_" .. name)
  if not ok then
    if opts.notify ~= false then
      vim.notify("Failed to apply colors_" .. name .. ": " .. tostring(err), vim.log.levels.WARN)
    end
    return nil
  end

  return name
end

function M.apply_env_or_default(default)
  default = default or M.default

  local env_name = normalize_theme_name(vim.env.DOTFILES_THEME)
  if env_name then
    local applied = M.apply_theme(env_name)
    if applied then
      return applied
    end

    vim.notify("DOTFILES_THEME=" .. env_name .. " did not resolve; falling back to " .. default, vim.log.levels.WARN)
  end

  return M.apply_theme(default, { notify = false })
end

-- Synchronous detect using DOTFILES_THEME when available, then the active
-- palette, then Neovim's current background mode.
function M.detect()
  local env_theme = M.env_theme()
  if env_theme then
    return env_theme
  end

  if M.active then
    if type(M.active.name) == "string" then
      return M.active.name
    end
    if type(M.active.bg) == "string" then
      local hex = M.active.bg:gsub("#", ""):lower()
      return M.registry[hex] or (is_light_bg(M.active.bg) and "light" or "dark")
    end
  end

  return vim.o.background == "light" and "light" or "dark"
end

-- Async fallback/manual detect: query OSC 11 via /dev/tty, parse hex, lookup
-- registry, apply colorscheme.
-- When inside tmux, the query goes to tmux (which responds with tmux's bg).
-- When outside tmux, the query goes to wezterm directly.
function M.detect_and_apply()
  -- Listen for the terminal's OSC 11 response via TermResponse autocmd
  vim.api.nvim_create_autocmd("TermResponse", {
    once = true,
    callback = function(args)
      local seq = args.data.sequence or ""
      local r, g, b = seq:match("\027%]11;rgb:(%x+)/(%x+)/(%x+)")
      if r and g and b then
        local hex = string.format("%s%s%s", r:sub(1, 2), g:sub(1, 2), b:sub(1, 2)):lower()
        local name = M.registry[hex] or M.default
        vim.schedule(function()
          local applied = M.apply_theme(name, { notify = false }) or M.apply_theme(M.default, { notify = false })
          if applied then
            vim.cmd(string.format("echom '[colors] %s (hex=%s)'", applied, hex))
          end
        end)
      else
        local esc = seq:gsub("[%c]", function(c)
          return string.format("\\x%02x", c:byte())
        end)
        vim.schedule(function()
          vim.cmd("echom '[colors] no OSC 11 match: " .. vim.fn.escape(esc, "'\\") .. "'")
        end)
      end
    end,
  })
  -- Send the OSC 11 query
  io.stdout:write("\027]11;?\027\\")
  io.stdout:flush()
end

function M.apply(palette_name)
  -- Force re-require to allow switching
  package.loaded["colors." .. palette_name] = nil
  local c = require("colors." .. palette_name)
  M.active = c

  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.g.colors_name = "colors_" .. palette_name

  -- Determine light/dark from palette background luminance.
  local is_light = is_light_bg(c.bg)
  vim.o.background = is_light and "light" or "dark"
  local active_window_edge = c.pane_active_border_fg or (is_light and "#000000" or "#ffffff")

  -- Cursor shape
  vim.opt.guicursor = "n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor"

  -- Terminal colors (16-color ANSI palette)
  vim.g.terminal_color_0 = c.bg
  vim.g.terminal_color_1 = c.red
  vim.g.terminal_color_2 = c.green
  vim.g.terminal_color_3 = c.wood
  vim.g.terminal_color_4 = c.blue
  vim.g.terminal_color_5 = c.magenta
  vim.g.terminal_color_6 = c.teal
  vim.g.terminal_color_7 = c.fg
  vim.g.terminal_color_8 = c.gray
  vim.g.terminal_color_9 = c.bright_red or c.red
  vim.g.terminal_color_10 = c.bright_green or c.green
  vim.g.terminal_color_11 = c.bright_yellow or c.wood
  vim.g.terminal_color_12 = c.bright_blue or c.blue
  vim.g.terminal_color_13 = c.bright_magenta or c.magenta
  vim.g.terminal_color_14 = c.bright_cyan or c.teal
  vim.g.terminal_color_15 = c.dim

  -- Convenience: bg tint fields default to nil (ignored by nvim_set_hl)
  local bg_string = c.bg_string
  local bg_comment = is_light and c.bg_comment or "NONE"
  local bg_const = c.bg_const
  local bg_def = c.bg_def
  local markdown_code_bg = blend_hex(c.bg_cur, c.bg, 0.40)
  -- Light themes mark inline code with green text; dark themes use a tint.
  local markdown_inline_code = is_light and { fg = c.green } or { bg = markdown_code_bg }
  local hop_label_fg = is_light and c.bg or c.red
  local hop_label_bg = is_light and c.red or nil
  local hop_label_bg_2 = is_light and blend_hex(c.red, c.bg, 0.72) or nil

  -- Blended from the palette the way difftastic derives its own diff colours:
  -- one opacity for full lines, a stronger one for inline spans.
  local diff_line_blend = 0.19
  local diff_span_blend = 0.38

  local diff_add_bg = blend_hex(c.green, c.bg, diff_line_blend)
  -- Red carries more chroma than the green, so it blends lighter to match.
  local diff_delete_bg = blend_hex(c.red, c.bg, 0.14)
  -- Cool hue for change: at these opacities wood desaturates into the delete
  -- rose. Blue reads stronger than the sage and rose, so it blends lighter.
  local diff_change_bg = blend_hex(c.blue, c.bg, 0.12)
  local diff_text_bg = blend_hex(c.blue, c.bg, 0.22)
  -- Filler hatching is structural, not a deletion, so it stays neutral.
  local diff_filler_fg = blend_hex(c.fg, c.bg, is_light and 0.30 or 0.38)
  local dropbar_current_bg = blend_hex(c.fg, c.bg_float, is_light and 0.12 or 0.16)
  local dropbar_hover_bg = blend_hex(c.wood, c.bg_float, is_light and 0.18 or 0.28)
  local dropbar_thumb_bg = blend_hex(c.dim, c.bg_float, is_light and 0.35 or 0.45)
  local dap_stopped_bg = is_light and blend_hex(c.green, c.bg, 0.08) or blend_hex(c.green, c.bg, 0.18)
  local dap_selected_bg = is_light and blend_hex(c.blue, c.bg, 0.08) or c.bg_cur
  local dap_muted_fg = is_light and blend_hex(c.dim, c.bg, 0.72) or c.dim
  local neotest_indent_fg = is_light and blend_hex(c.dim, c.bg, 0.45) or c.gray
  local neotest_marker_fg = is_light and blend_hex(c.dim, c.bg, 0.62) or c.dim
  local neotest_focus_bg = is_light and blend_hex(c.blue, c.bg, 0.08) or c.bg_cur

  -- Base text color for "everything else" in alabaster philosophy
  local base = c.fg

  -- Build highlight groups
  local theme = {
    -- Editor UI
    Normal = { fg = c.fg, bg = c.bg },
    NormalFloat = { bg = c.bg_float },
    FloatBorder = { fg = c.dim, bg = c.bg_float },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.bg_cur },
    CursorColumn = { bg = c.bg_cur },
    CursorLineNr = { fg = c.fg },
    LineNr = { fg = c.gray },
    SignColumn = {},
    Visual = { bg = c.bg_vis },
    VisualNOS = { bg = c.bg_vis },
    Search = { bg = c.bg_vis },
    IncSearch = { bg = c.wood, fg = c.bg },
    CurSearch = { bg = c.wood, fg = c.bg },
    ColorColumn = { bg = c.bg_cur },
    VirtColumn = { fg = c.gray },
    Conceal = { fg = c.dim },
    NonText = { fg = c.gray },

    -- Signature help rendered as virtual lines by config.signature. The float
    -- background carries across every chunk so the box reads as one block.
    SignatureBorder = { fg = c.dim, bg = c.bg_float },
    SignatureTitle = { fg = c.magenta, bg = c.bg_float },
    SignatureBody = { fg = c.fg, bg = c.bg_float },
    SignatureParam = { fg = c.fg, bg = c.bg_float, bold = true },
    SignatureActiveParam = { fg = c.magenta, bg = c.bg_float, bold = true },
    SignatureType = { fg = c.dim, bg = c.bg_float },
    SignaturePunct = { fg = c.gray, bg = c.bg_float },
    SignatureDoc = { fg = c.dim, bg = c.bg_float },

    EndOfBuffer = { fg = c.gray },
    SpecialKey = { fg = c.teal },
    Directory = { fg = c.blue },
    Title = { fg = c.magenta },
    ErrorMsg = { fg = c.red, bg = c.bg },
    ModeMsg = { fg = c.green, bg = c.bg, bold = true },
    MsgArea = { fg = c.fg, bg = c.bg },
    MsgSeparator = { fg = c.gray, bg = c.bg },
    WarningMsg = { fg = c.wood, bold = true },
    MoreMsg = { fg = c.green, bold = true },
    Question = { fg = c.green },
    VertSplit = { fg = c.gray },
    WinSeparator = { fg = c.gray },
    ColorfulWinSep = { fg = active_window_edge, bold = true },
    WinBar = { fg = base, bg = c.bg, bold = true },
    WinBarNC = { fg = c.dim, bg = c.bg },
    DotfilesWinbarProjectTitle = { fg = c.fg, bg = c.bg, bold = true },
    DotfilesWinbarProjectPath = { fg = c.dim, bg = c.bg },
    DropBarInactivePath = { fg = c.dim, bg = c.bg, bold = true },
    DropBarCurrentContext = { fg = c.fg, bg = dropbar_current_bg, bold = true },
    DropBarCurrentContextIcon = { bg = dropbar_current_bg, bold = true },
    DropBarCurrentContextName = { fg = c.fg, bg = dropbar_current_bg, bold = true },
    DropBarHover = { bg = dropbar_hover_bg },
    DropBarIconUIIndicator = { fg = c.wood, bg = "NONE" },
    DropBarIconUISeparator = { fg = c.dim, bg = "NONE" },
    DropBarIconUISeparatorNC = { fg = c.dim, bg = "NONE" },
    DropBarIconUISeparatorMenu = { fg = c.dim, bg = "NONE" },
    DropBarMenuCurrentContext = { fg = c.fg, bg = dropbar_current_bg, bold = true },
    DropBarMenuFloatBorder = { fg = c.dim, bg = c.bg_float },
    DropBarMenuHoverEntry = { bg = dropbar_hover_bg },
    DropBarMenuHoverIcon = { fg = c.wood, bg = dropbar_hover_bg, bold = true },
    DropBarMenuHoverSymbol = { fg = c.fg, bg = dropbar_hover_bg, bold = true },
    DropBarMenuNormalFloat = { fg = c.fg, bg = c.bg_float },
    DropBarMenuSbar = { bg = c.bg_float },
    DropBarMenuThumb = { bg = dropbar_thumb_bg },

    -- Completion / wild menu
    WildMenu = { fg = c.bg, bg = c.fg, bold = true },
    Pmenu = { fg = c.fg, bg = c.bg_float },
    PmenuSel = { fg = c.bg, bg = c.fg, bold = true },
    PmenuSbar = { bg = c.bg_float },
    PmenuThumb = { bg = c.gray },

    -- Statusline / tabline
    StatusLine = { fg = c.fg, bg = c.bg_float },
    StatusLineNC = { fg = c.dim, bg = c.bg_float },
    TabLine = { fg = c.dim, bg = c.bg_float },
    TabLineFill = { bg = c.bg_float },
    TabLineSel = { fg = c.blue, bg = c.bg_float },

    -- Folds
    Folded = { fg = c.dim, bg = c.bg_cur },
    FoldColumn = { fg = c.gray, bg = c.bg },

    -- Diff
    DiffAdd = { bg = diff_add_bg },
    DiffDelete = { bg = diff_delete_bg },
    DiffChange = { bg = diff_change_bg },
    DiffText = { bg = diff_text_bg },
    diffAdded = { fg = c.green },
    diffRemoved = { fg = c.red },
    diffChanged = { fg = c.wood },
    DiffviewDiffAdd = { bg = diff_add_bg },
    DiffviewDiffAddAsDelete = { bg = diff_delete_bg },
    DiffviewDiffChange = { bg = diff_change_bg },
    DiffviewDiffText = { bg = diff_text_bg },
    -- Deleted rows in the unified inline layout. Defined rather than left
    -- linked to DiffDelete, which the diff namespaces make pale for filler.
    DiffviewDiffDelete = { bg = diff_delete_bg },
    DiffviewDiffDeleteDim = { fg = diff_filler_fg },
    -- Fenced ```diff blocks, which the diff parser highlights line by line.
    ["@diff.plus"] = { fg = c.green, bg = diff_add_bg },
    ["@diff.minus"] = { fg = c.red, bg = diff_delete_bg },
    ["@diff.delta"] = { fg = c.wood, bg = diff_change_bg },

    -- Spell
    SpellBad = { undercurl = true, sp = c.red },
    SpellCap = { undercurl = true, sp = c.blue },
    SpellLocal = { undercurl = true, sp = c.teal },
    SpellRare = { undercurl = true, sp = c.magenta },

    -- Terminal
    TermCursorNC = { fg = c.bg, bg = c.fg },

    -- Match
    MatchParen = { underline = true, sp = c.wood },
    QuickFixLine = { bg = c.bg_cur },

    -- Syntax: Alabaster philosophy — only comments, strings, constants, definitions get color
    Comment = { fg = c.comment, bg = bg_comment, bold = true },
    Constant = { fg = c.magenta, bg = bg_const },
    String = { fg = c.green, bg = bg_string },
    Character = { fg = c.magenta, bg = bg_const },
    Number = { fg = c.magenta, bg = bg_const },
    Boolean = { fg = c.magenta, bg = bg_const },
    Float = { fg = c.magenta, bg = bg_const },

    Identifier = { fg = base },
    Function = { fg = c.blue, bg = bg_def },
    Statement = { fg = base },
    Conditional = { fg = base, bold = true },
    Repeat = { fg = base, bold = true },
    Label = { fg = c.blue, bg = bg_def },
    Operator = { fg = c.dim },
    Keyword = { fg = base, bold = true },
    Exception = { fg = base, bold = true },

    PreProc = { fg = base },
    Include = { fg = base },
    Define = { fg = base },
    Macro = { fg = base, bold = true },
    PreCondit = { fg = base },

    Type = { fg = c.teal },
    StorageClass = { fg = base },
    Structure = { fg = c.blue, bg = bg_def },
    Typedef = { fg = c.blue, bg = bg_def },

    Special = { fg = c.wood },
    SpecialComment = { fg = c.blue, bg = bg_comment },
    Delimiter = { fg = base },
    Underlined = { underline = true },
    Italic = { italic = true },
    Error = { fg = c.red, bold = true },
    Todo = { fg = c.wood, bold = true },

    -- Treesitter highlights
    ["@variable"] = { fg = base },
    ["@variable.builtin"] = { fg = base, bold = true },
    ["@variable.parameter"] = { fg = base },
    ["@variable.parameter.builtin"] = { fg = base, bold = true },
    ["@variable.member"] = { fg = base },
    ["@constant"] = { fg = c.magenta, bg = bg_const },
    ["@constant.builtin"] = { fg = c.magenta, bg = bg_const },
    ["@constant.macro"] = { fg = base },
    ["@module"] = { fg = base },
    ["@module.builtin"] = { fg = base, bold = true },
    ["@string"] = { fg = c.green, bg = bg_string },
    ["@string.regex"] = { fg = c.magenta, bg = c.bg_cur },
    ["@string.escape"] = { fg = c.magenta, bg = c.bg_cur },
    ["@character"] = { fg = c.magenta, bg = bg_const },
    ["@number"] = { fg = c.magenta, bg = bg_const },
    ["@boolean"] = { fg = c.magenta, bg = bg_const },
    ["@float"] = { fg = c.magenta, bg = bg_const },
    ["@function"] = { fg = base },
    ["@function.builtin"] = { fg = base, bold = true },
    ["@function.macro"] = { fg = base, bold = true },
    ["@function.call"] = { fg = base },
    ["@method"] = { fg = base },
    ["@method.call"] = { fg = base },
    ["@constructor"] = { fg = base },
    ["@keyword"] = { fg = base, bold = true },
    ["@keyword.function"] = { fg = base, bold = true },
    ["@keyword.operator"] = { fg = c.dim, bold = true },
    ["@keyword.return"] = { fg = base, bold = true },
    ["@conditional"] = { fg = base, bold = true },
    ["@repeat"] = { fg = base, bold = true },
    ["@label"] = { fg = base },
    ["@operator"] = { fg = c.dim },
    ["@exception"] = { fg = base, bold = true },
    ["@type"] = { fg = c.teal },
    ["@type.builtin"] = { fg = c.teal, bold = true },
    ["@type.definition"] = { fg = c.blue, bg = bg_def },
    ["@type.qualifier"] = { fg = base },
    ["@namespace"] = { fg = base },
    ["@include"] = { fg = base },
    ["@preproc"] = { fg = base },
    ["@attribute"] = {},
    ["@attribute.builtin"] = { bold = true },
    ["@field"] = { fg = base },
    ["@property"] = { fg = base },
    ["@parameter"] = { fg = base },
    ["@tag"] = { fg = base },
    ["@tag.builtin"] = { fg = base, bold = true },
    ["@tag.delimiter"] = { fg = c.dim },
    ["@tag.attribute"] = { fg = base },
    ["@punctuation.bracket"] = { fg = base },
    ["@punctuation.delimiter"] = { fg = base },
    ["@punctuation.special"] = { fg = c.dim },
    ["@punctuation"] = { fg = base },
    ["@text"] = { fg = base },
    ["@text.note"] = { fg = c.blue, bg = c.bg_cur },
    ["@text.warning"] = { fg = c.wood, bold = true },
    ["@markup.heading.1.markdown"] = { fg = c.magenta, bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.blue, bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.teal, bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.fg, bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.fg, bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.fg, bold = true },
    ["@markup.raw.block.markdown"] = { bg = markdown_code_bg },
    ["@markup.raw.markdown_inline"] = markdown_inline_code,
    ["@markup.raw.inline.markdown_inline"] = markdown_inline_code,

    -- Comment annotations
    ["@comment.note"] = { fg = c.blue, bold = true },
    ["@comment.todo"] = { fg = c.wood, bold = true },
    ["@comment.warning"] = { fg = c.red, bold = true },
    ["@comment.error"] = { fg = c.red, bold = true },
    ["@comment.hint"] = { fg = c.green, bold = true },

    -- LSP semantic tokens
    ["@lsp.mod.declaration"] = { fg = base },
    ["@lsp.type.enumMember"] = { fg = base },
    ["@lsp.type.function"] = { fg = base },
    ["@lsp.type.method"] = { fg = base },
    ["@lsp.type.selfKeyword"] = { fg = base },
    ["@lsp.typemod.class.declaration"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.class.definition"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.enum.declaration"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.enumMember.defaultLibrary"] = { fg = base },
    ["@lsp.typemod.function.declaration"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.function.definition"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.macro.declaration"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.method.declaration"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.selfKeyword"] = { fg = base },
    ["@lsp.typemod.struct.declaration"] = { fg = c.blue, bg = bg_def },
    ["@lsp.typemod.type.declaration"] = { fg = c.blue, bg = bg_def },

    -- Alabaster custom groups (used by treesitter queries)
    ["@AlabasterBase"] = { fg = base },
    ["@comment"] = { fg = c.comment, bg = bg_comment, bold = true },
    ["@AlabasterComment"] = { fg = c.comment, bg = bg_comment, bold = true },
    ["@AlabasterConstant"] = { fg = c.magenta, bg = bg_const },
    -- Type-position ALL_CAPS names: teal like any type ref; explicit bg clears
    -- the constant tint the stock query would otherwise leak underneath.
    ["@AlabasterTypeRef"] = { fg = c.teal, bg = c.bg },
    ["@AlabasterDefinition"] = { fg = c.blue, bg = bg_def },
    ["@AlabasterDocString"] = { fg = c.green, bg = "NONE" },
    ["@AlabasterMethodDeclaration"] = { fg = c.blue },
    ["@AlabasterPunct"] = { fg = c.dim },
    ["@AlabasterPunctuation"] = { fg = c.dim },
    ["@AlabasterString"] = { fg = c.green, bg = bg_string },
    ["@AlabasterStringInterpolation"] = { bg = bg_string },
    ["@AlabasterHashbang"] = { fg = c.dim },
    AlabasterStringLeadingWhitespace = { bg = bg_string and c.bg or "NONE" },

    -- Diagnostics
    DiagnosticError = { fg = c.red, bold = true },
    DiagnosticWarn = { fg = c.wood, bold = true },
    DiagnosticInfo = { fg = c.blue, bold = true },
    DiagnosticHint = { fg = c.teal, bold = true },
    DiagnosticVirtualTextError = { fg = c.red, bold = true },
    DiagnosticVirtualTextWarn = { fg = c.wood, bold = true },
    DiagnosticVirtualTextInfo = { fg = c.blue, bold = true },
    DiagnosticVirtualTextHint = { fg = c.teal, bold = true },
    DiagnosticUnderlineError = { sp = c.red, underline = true },
    DiagnosticUnderlineWarn = { sp = c.wood, underline = true },
    DiagnosticUnderlineInfo = { sp = c.wood, underline = true },
    DiagnosticUnderlineHint = { sp = c.wood, underline = true },
    -- LSP tags like "unnecessary" and "deprecated" override severity underlines,
    -- so define them explicitly instead of inheriting Neovim's default Comment link.
    DiagnosticUnnecessary = { sp = c.wood, underline = true },
    DiagnosticDeprecated = { sp = c.wood, underline = true },
    DiagnosticFloatingError = { fg = c.red, bold = true },
    DiagnosticFloatingWarn = { fg = c.wood, bold = true },
    DiagnosticFloatingInfo = { fg = c.blue, bold = true },
    DiagnosticFloatingHint = { fg = c.teal, bold = true },
    DiagnosticSignError = { fg = c.red, bold = true },
    DiagnosticSignWarn = { fg = c.wood, bold = true },
    DiagnosticSignInfo = { fg = c.blue, bold = true },
    DiagnosticSignHint = { fg = c.teal, bold = true },

    -- LSP references
    LspReferenceText = { bg = c.bg_cur },
    LspReferenceRead = { bg = c.bg_cur, underline = true, sp = c.blue },
    LspReferenceWrite = { bg = c.bg_cur, underline = true, sp = c.red },
    LspCodeLens = { fg = c.gray },
    LspCodeLensSeparator = { fg = c.gray },

    -- Git signs
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.wood },
    GitSignsDelete = { fg = c.red },

    -- Markdown headers: magenta → blue → teal → neutral
    htmlH1 = { fg = c.magenta, bold = true },
    htmlH2 = { fg = c.blue, bold = true },
    htmlH3 = { fg = c.teal, bold = true },
    htmlH4 = { fg = c.fg, bold = true },
    htmlH5 = { fg = c.fg, bold = true },
    htmlH6 = { fg = c.fg, bold = true },

    -- Markdown text styles (prevent bg override on CursorLine)
    htmlBold = { fg = c.fg, bold = true },
    htmlItalic = { fg = c.fg, italic = true },
    htmlBoldItalic = { fg = c.fg, bold = true, italic = true },
    AlabasterMarkdownCodeBlock = { bg = markdown_code_bg },
    mkdCode = { bg = markdown_code_bg },
    mkdCodeDelimiter = { bg = markdown_code_bg },
    mkdCodeStart = { bg = markdown_code_bg },
    mkdCodeEnd = { bg = markdown_code_bg },
    markdownCode = is_light and markdown_inline_code or { fg = c.wood, bg = markdown_code_bg },
    markdownCodeDelimiter = markdown_inline_code,

    -- Language-specific
    rustFoldBraces = { fg = base },
    -- Neovim's builtin TypeScript syntax links punctuation groups to
    -- Function/Exception/Operator. Keep them neutral instead.
    typescriptBraces = { link = "Delimiter" },
    typescriptBOMWindowMethod = { link = "Identifier" },
    typescriptBOMWindowProp = { link = "Identifier" },
    typescriptDestructureVariable = { link = "Function" },
    typescriptDestructureAs = { link = "Delimiter" },
    typescriptEndColons = { link = "Delimiter" },
    typescriptFuncComma = { link = "Delimiter" },
    typescriptIdentifier = { link = "Identifier" },
    typescriptObjectLabel = { link = "Identifier" },
    typescriptObjectColon = { link = "Delimiter" },
    typescriptParens = { link = "Delimiter" },
    typescriptVariableDeclaration = { link = "Function" },
    tsxCloseString = { link = "Delimiter" },
    tsxCloseTag = { link = "Delimiter" },
    tsxTag = { link = "Delimiter" },

    -- Plugin: Telescope
    TelescopeBorder = { fg = c.gray },
    TelescopeMatching = { fg = c.wood },
    TelescopeMultiSelection = { fg = c.magenta },
    TelescopePromptPrefix = { fg = c.blue },
    TelescopeTitle = { fg = c.comment },
    TelescopeResultsTitle = { fg = c.wood },

    -- Plugin: cmp
    CmpItemMenuDefault = { fg = c.magenta },

    -- Plugin: Hop
    HopNextKey = { fg = hop_label_fg, bg = hop_label_bg, bold = true },
    HopNextKey1 = { fg = hop_label_fg, bg = hop_label_bg, bold = true },
    HopNextKey2 = { fg = hop_label_fg, bg = hop_label_bg_2, bold = is_light or nil },
    HopUnmatched = { fg = blend_hex(c.fg, c.gray, 0.65) },

    -- Plugin: Neogit
    NeogitPopupActionDisabled = { fg = c.dim },
    NeogitPopupActionKey = { fg = c.magenta },
    NeogitPopupOptionDisabled = { fg = c.dim },
    NeogitPopupOptionKey = { fg = c.blue },
    NeogitPopupSwitchDisabled = { fg = c.dim },
    NeogitPopupSwitchEnabled = { fg = c.teal },
    NeogitPopupSwitchKey = { fg = c.magenta },

    -- Plugin: nvim-dap / nvim-dap-ui
    DapBreakpoint = { fg = c.red, bold = true },
    DapBreakpointCondition = { fg = c.wood, bold = true },
    DapBreakpointRejected = { fg = c.dim },
    DapLogPoint = { fg = c.blue },
    DapStopped = { fg = c.green, bold = true },
    DapStoppedLine = { bg = dap_stopped_bg },
    DapUIDecoration = { fg = c.gray },
    DapUIFloatBorder = { fg = c.gray, bg = c.bg_float },
    DapUIBreakpointsCurrentLine = { fg = c.blue, bg = dap_selected_bg, bold = true },
    DapUIBreakpointsDisabledLine = { fg = c.gray },
    DapUIBreakpointsInfo = { fg = c.green },
    DapUIBreakpointsLine = { fg = c.fg },
    DapUIBreakpointsPath = { fg = c.blue, bold = true },
    DapUICurrentFrameName = { fg = c.green, bold = true },
    DapUIFrameName = { fg = c.fg },
    DapUILineNumber = { fg = c.blue },
    DapUIModifiedValue = { fg = c.wood, bold = true },
    DapUIScope = { fg = c.blue, bold = true },
    DapUISource = { fg = c.magenta },
    DapUIStoppedThread = { fg = c.green, bold = true },
    DapUIThread = { fg = c.green },
    DapUIType = { fg = c.teal },
    DapUIUnavailable = { fg = c.gray },
    DapUIValue = { fg = c.fg },
    DapUIVariable = { fg = c.fg },
    DapUIWatchesEmpty = { fg = c.gray },
    DapUIWatchesError = { fg = c.red },
    DapUIWatchesValue = { fg = c.green },
    DapUIWinSelect = { fg = c.blue, bold = true },
    DapUIPlayPause = { fg = c.green, bold = true },
    DapUIRestart = { fg = c.green, bold = true },
    DapUIStop = { fg = c.red, bold = true },
    DapUIStepBack = { fg = c.blue, bold = true },
    DapUIStepInto = { fg = c.blue, bold = true },
    DapUIStepOut = { fg = c.blue, bold = true },
    DapUIStepOver = { fg = c.blue, bold = true },
    DapUIPlayPauseNC = { fg = dap_muted_fg },
    DapUIRestartNC = { fg = dap_muted_fg },
    DapUIStopNC = { fg = dap_muted_fg },
    DapUIStepBackNC = { fg = dap_muted_fg },
    DapUIStepIntoNC = { fg = dap_muted_fg },
    DapUIStepOutNC = { fg = dap_muted_fg },
    DapUIStepOverNC = { fg = dap_muted_fg },

    -- Plugin: neotest
    -- Override neotest's high-chroma defaults so the summary tree follows the
    -- active palette, especially on light themes.
    NeotestAdapterName = { fg = c.magenta, bold = true },
    NeotestBorder = { fg = c.gray, bg = c.bg_float },
    NeotestDir = { fg = c.blue },
    NeotestExpandMarker = { fg = neotest_marker_fg },
    NeotestFailed = { fg = c.red, bold = true },
    NeotestFile = { fg = c.teal },
    NeotestFocused = { fg = c.fg, bg = neotest_focus_bg, bold = true },
    NeotestIndent = { fg = neotest_indent_fg },
    NeotestMarked = { fg = c.wood, bold = true },
    NeotestNamespace = { fg = c.blue },
    NeotestPassed = { fg = c.green, bold = true },
    NeotestRunning = { fg = c.wood, bold = true },
    NeotestSkipped = { fg = c.teal },
    NeotestTarget = { fg = c.red, bold = true },
    NeotestTest = { fg = c.fg },
    NeotestUnknown = { fg = c.dim },
    NeotestWatching = { fg = c.wood },
    NeotestWinSelect = { fg = c.blue, bold = true },
  }

  -- Apply all highlights
  for group, hl in pairs(theme) do
    vim.api.nvim_set_hl(0, group, hl)
  end

  -- These syntax groups use Alabaster background tints in light themes.
  -- Window-local contexts can retain their foreground/style while suppressing
  -- the tint, without changing the global colorscheme.
  local tinted_syntax_groups = {
    "Comment",
    "Constant",
    "String",
    "Character",
    "Number",
    "Boolean",
    "Float",
    "Function",
    "Label",
    "Structure",
    "Typedef",
    "SpecialComment",
    "@comment",
    "@constant",
    "@constant.builtin",
    "@string",
    "@string.regex",
    "@string.escape",
    "@character",
    "@number",
    "@boolean",
    "@float",
    "@type.definition",
    "@lsp.typemod.class.declaration",
    "@lsp.typemod.class.definition",
    "@lsp.typemod.enum.declaration",
    "@lsp.typemod.function.declaration",
    "@lsp.typemod.function.definition",
    "@lsp.typemod.macro.declaration",
    "@lsp.typemod.method.declaration",
    "@lsp.typemod.struct.declaration",
    "@lsp.typemod.type.declaration",
    "@AlabasterComment",
    "@AlabasterConstant",
    "@AlabasterTypeRef",
    "@AlabasterDefinition",
    "@AlabasterDocString",
    "@AlabasterMethodDeclaration",
    "@AlabasterString",
    "@AlabasterStringInterpolation",
  }

  local syntax_no_bg_theme = {}
  for _, group in ipairs(tinted_syntax_groups) do
    if theme[group] then
      syntax_no_bg_theme[group] = vim.tbl_extend("force", {}, theme[group], { bg = "NONE" })
    end
  end

  -- Markdown windows should keep syntax foregrounds but not the Alabaster bg tints.
  local markdown_theme = vim.tbl_extend("force", {}, syntax_no_bg_theme, {
    ["@markup.heading.1.markdown"] = { fg = c.magenta, bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.blue, bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.teal, bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.fg, bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.fg, bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.fg, bold = true },
    ["@markup.raw.block.markdown"] = { bg = markdown_code_bg },
    ["@markup.raw.markdown_inline"] = markdown_inline_code,
    ["@markup.raw.inline.markdown_inline"] = markdown_inline_code,
  })

  -- Diff viewers keep their own line-level diff backgrounds. On light themes,
  -- suppress syntax tints so they do not compete with those backgrounds.
  -- Dark themes use the normal syntax definitions in the same namespace so
  -- an open view updates correctly when the colorscheme changes.
  local diff_theme = {}
  for _, group in ipairs(tinted_syntax_groups) do
    if theme[group] then
      diff_theme[group] = is_light and syntax_no_bg_theme[group] or theme[group]
    end
  end

  local zen_theme = {
    NormalFloat = { fg = c.fg, bg = c.bg },
    EndOfBuffer = { fg = c.gray, bg = c.bg },
  }

  -- Native diff paints lines unique to a buffer with DiffAdd in both panes, so
  -- the left pane renders them as deletions. Changed lines exist on both sides
  -- and keep the shared change colours. Filler stays pale on both.
  -- Diff viewers paint full-line backgrounds, which hide a background-based
  -- cursor line. Underline it instead.
  local diff_cursor_line = { underline = true, sp = c.gray }

  local diff_sides = {
    a = {
      DiffAdd = { bg = diff_delete_bg },
      DiffDelete = { fg = diff_filler_fg },
      CursorLine = diff_cursor_line,
    },
    b = {
      DiffDelete = { fg = diff_filler_fg },
      CursorLine = diff_cursor_line,
    },
  }

  local diff_themes = {}
  for side, overrides in pairs(diff_sides) do
    diff_themes[side] = vim.tbl_extend("force", {}, diff_theme, overrides)
  end

  windows.apply_highlights(markdown_theme, zen_theme, diff_themes)

  -- fzf.vim reads g:fzf_colors and translates these groups into --color flags.
  -- Keep it in sync with the active palette so :Files/:Buffers/:Rg follow the theme.
  vim.g.fzf_colors = {
    fg = { "fg", "Normal" },
    bg = { "bg", "NormalFloat", "Normal" },
    ["preview-fg"] = { "fg", "Normal" },
    ["preview-bg"] = { "bg", "NormalFloat", "Normal" },
    gutter = { "bg", "NormalFloat", "Normal" },
    hl = { "fg", "Comment" },
    ["fg+"] = { "fg", "CursorLine", "CursorColumn", "Normal" },
    ["bg+"] = { "bg", "CursorLine", "CursorColumn", "Visual" },
    ["hl+"] = { "fg", "Function" },
    info = { "fg", "Type" },
    border = { "fg", "FloatBorder" },
    prompt = { "fg", "Function" },
    pointer = { "fg", "Constant" },
    marker = { "fg", "Constant" },
    spinner = { "fg", "Type" },
    header = { "fg", "Comment" },
    query = { "fg", "Normal" },
    disabled = { "fg", "Comment" },
  }

  -- fzf.vim previews shell out to bat; use the ANSI theme so preview syntax
  -- follows the current terminal palette we set above.
  vim.env.BAT_THEME = "ansi"

  -- Clear sign column background
  vim.api.nvim_set_hl(0, "SignColumn", { bg = "NONE" })
end

function M.apply_window_highlights(win)
  windows.apply_window_highlights(win)
end

function M.apply_diff_window_highlights(win, side)
  windows.apply_diff_window_highlights(win, side)
end

return M
